// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooCluster) DeepCopyInto(out *OdooCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooCluster.
func (in *OdooCluster) DeepCopy() *OdooCluster {
	if in == nil {
		return nil
	}
	out := new(OdooCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterList) DeepCopyInto(out *OdooClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterList.
func (in *OdooClusterList) DeepCopy() *OdooClusterList {
	if in == nil {
		return nil
	}
	out := new(OdooClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterResourceSpec) DeepCopyInto(out *OdooClusterResourceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterResourceSpec.
func (in *OdooClusterResourceSpec) DeepCopy() *OdooClusterResourceSpec {
	if in == nil {
		return nil
	}
	out := new(OdooClusterResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterSpec) DeepCopyInto(out *OdooClusterSpec) {
	*out = *in
	out.ImageSpec = in.ImageSpec
	out.DbSpec = in.DbSpec
	out.ResourceSpec = in.ResourceSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterSpec.
func (in *OdooClusterSpec) DeepCopy() *OdooClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OdooClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterSpecDbSpec) DeepCopyInto(out *OdooClusterSpecDbSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterSpecDbSpec.
func (in *OdooClusterSpecDbSpec) DeepCopy() *OdooClusterSpecDbSpec {
	if in == nil {
		return nil
	}
	out := new(OdooClusterSpecDbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterSpecImage) DeepCopyInto(out *OdooClusterSpecImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterSpecImage.
func (in *OdooClusterSpecImage) DeepCopy() *OdooClusterSpecImage {
	if in == nil {
		return nil
	}
	out := new(OdooClusterSpecImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooClusterStatus) DeepCopyInto(out *OdooClusterStatus) {
	*out = *in
	if in.ImageVersions != nil {
		in, out := &in.ImageVersions, &out.ImageVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooClusterStatus.
func (in *OdooClusterStatus) DeepCopy() *OdooClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OdooClusterStatus)
	in.DeepCopyInto(out)
	return out
}
